# Generated by Django 5.1.8 on 2026-05-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_text', models.TextField(help_text='Поддерживаются переносы строк (Enter). Используйте |linebreaks в шаблоне.', verbose_name='Вводный текст')),
                ('photo', models.ImageField(blank=True, help_text='Рекомендуемый размер: 400×400 px, формат WEBP/JPEG.', null=True, upload_to='about/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'О себе',
                'verbose_name_plural': 'О себе',
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Например: "50 000", "12+", "8". Хранится как строка.', max_length=50, verbose_name='Значение')),
                ('label', models.CharField(help_text='Например: "м² сданных объектов", "лет опыта".', max_length=200, verbose_name='Подпись')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_username', models.CharField(blank=True, help_text='Без символа @. Например: ivan_ivanov', max_length=100, verbose_name='Telegram username')),
                ('max_url', models.URLField(blank=True, help_text='Полный URL профиля в мессенджере Max (ex-VK Мессенджер).', verbose_name='Ссылка Max')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('kind', models.CharField(choices=[('construction', 'Строительство'), ('it', 'IT')], max_length=20, verbose_name='Тип')),
                ('description', models.TextField(verbose_name='Описание')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Изображение')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Меньшее число — выше в списке.', verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['order', '-year'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Навык')),
                ('category', models.CharField(choices=[('it', 'IT-разработка'), ('construction', 'Строительство'), ('security', 'Кибербезопасность')], max_length=20, verbose_name='Категория')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
                'ordering': ['category', 'order'],
            },
        ),
    ]
