# Generated by Django 5.1.8 on 2026-06-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='live_url',
            field=models.URLField(blank=True, help_text='Живой сайт / демо, если есть.', verbose_name='Ссылка на демо'),
        ),
        migrations.AddField(
            model_name='project',
            name='repo_url',
            field=models.URLField(blank=True, help_text='GitHub и т.п. Оставьте пустым для приватных проектов.', verbose_name='Ссылка на репозиторий'),
        ),
    ]
